server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true    #\u4E0B\u5212\u7EBF\u8F6C\u9A7C\u5CF0

#logging:
#  level:
#    root: info #\u65E5\u5FD7\u914D\u7F6EDEBUG,INFO,WARN,ERROR
#    com.zben.miaosha: debug
