spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true    #下划线转驼峰
server:
  port: 8080
  tomcat:
    max-threads: 10000      #设置tomcat最大并发数
    max-connections: 10000
